// Generated by CoffeeScript 1.3.3
(function() {
  var Scope, extend, last, _ref;

  _ref = require('./helpers'), extend = _ref.extend, last = _ref.last;

  exports.Scope = Scope = (function() {

    Scope.root = null;

    function Scope(parent, expressions, method) {
      this.parent = parent;
      this.expressions = expressions;
      this.method = method;
      this.variables = [
        {
          name: 'arguments',
          type: 'arguments'
        }
      ];
      this.positions = {};
      if (!this.parent) {
        Scope.root = this;
      }
    }

    Scope.prototype.add = function(name, type, immediate) {
      if (this.shared && !immediate) {
        return this.parent.add(name, type, immediate);
      }
      if (Object.prototype.hasOwnProperty.call(this.positions, name)) {
        return this.variables[this.positions[name]].type = type;
      } else {
        return this.positions[name] = this.variables.push({
          name: name,
          type: type
        }) - 1;
      }
    };

    Scope.prototype.namedMethod = function() {
      if (this.method.name || !this.parent) {
        return this.method;
      }
      return this.parent.namedMethod();
    };

    Scope.prototype.find = function(name) {
      if (this.check(name)) {
        return true;
      }
      this.add(name, 'var');
      return false;
    };

    Scope.prototype.parameter = function(name) {
      if (this.shared && this.parent.check(name, true)) {
        return;
      }
      return this.add(name, 'param');
    };

    Scope.prototype.check = function(name) {
      var _ref1;
      return !!(this.type(name) || ((_ref1 = this.parent) != null ? _ref1.check(name) : void 0));
    };

    Scope.prototype.is_dim = function(name) {
      var t, v, _i, _len, _ref1;
      t = void 0;
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.name === name) {
          t = v.type;
        }
      }
      if (t) {
        return t === 'uwsc_dim' || t === 'uwsc_const' || t === 'uwsc_public';
      }
      if (this.parent) {
        return this.parent.is_const(name);
      }
      return void 0;
    };

    Scope.prototype.is_const = function(name) {
      var t, v, _i, _len, _ref1;
      t = void 0;
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.name === name) {
          t = v.type;
        }
      }
      if (t) {
        return t === 'uwsc_const';
      }
      if (this.parent) {
        return this.parent.is_const(name);
      }
      return void 0;
    };

    Scope.prototype.is_public = function(name) {
      var t, v, _i, _len, _ref1;
      t = void 0;
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.name === name) {
          t = v.type;
        }
      }
      if (t) {
        return t === 'uwsc_public';
      }
      if (this.parent) {
        return this.parent.is_public(name);
      }
      return void 0;
    };

    Scope.prototype.set_const_val = function(name, val) {
      var v, _i, _len, _ref1;
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (!(v.name === name && (v.type = 'uwsc_const'))) {
          continue;
        }
        v._val = val;
        return;
      }
      if (this.parent) {
        return this.parent.set_const_val(name);
      }
    };

    Scope.prototype.get_const_val = function(name) {
      var ans, v, _i, _len, _ref1;
      ans = void 0;
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.name === name && (v.type = 'uwsc_const')) {
          return v._val;
        }
      }
      if (this.parent) {
        return this.parent.get_const_val(name);
      }
      return void 0;
    };

    Scope.prototype.temporary = function(name, index) {
      if (name.length > 1) {
        return '_' + name + (index > 1 ? index - 1 : '');
      } else {
        return '_' + (index + parseInt(name, 36)).toString(36).replace(/\d/g, 'a');
      }
    };

    Scope.prototype.type = function(name) {
      var v, _i, _len, _ref1;
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.name === name) {
          return v.type;
        }
      }
      return null;
    };

    Scope.prototype.freeVariable = function(name, reserve) {
      var index, temp;
      if (reserve == null) {
        reserve = true;
      }
      index = 0;
      while (this.check((temp = this.temporary(name, index)))) {
        index++;
      }
      if (reserve) {
        this.add(temp, 'var', true);
      }
      return temp;
    };

    Scope.prototype.assign = function(name, value) {
      this.add(name, {
        value: value,
        assigned: true
      }, true);
      return this.hasAssignments = true;
    };

    Scope.prototype.hasDeclarations = function() {
      return !!this.declaredVariables().length;
    };

    Scope.prototype.declaredVariables = function() {
      var realVars, tempVars, v, _i, _len, _ref1;
      realVars = [];
      tempVars = [];
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.type === 'var') {
          (v.name.charAt(0) === '_' ? tempVars : realVars).push(v.name);
        }
      }
      return realVars.sort().concat(tempVars.sort());
    };

    Scope.prototype.assignedVariables = function() {
      var v, _i, _len, _ref1, _results;
      _ref1 = this.variables;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (v.type.assigned) {
          _results.push("" + v.name + " = " + v.type.value);
        }
      }
      return _results;
    };

    Scope.prototype.show_vars = function() {
      var ans, v, _i, _len, _ref1;
      ans = '';
      _ref1 = this.variables;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        ans = ans + v.name + ", ";
      }
      return ans;
    };

    Scope.prototype.my_concat_hash = function(h0, h1) {
      var ans, k, _i, _j, _len, _len1, _ref1, _ref2;
      ans = [];
      _ref1 = h0.keys;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        k = _ref1[_i];
        ans[k] = h0[k];
      }
      _ref2 = h1.keys;
      for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
        k = _ref2[_j];
        ans[k] = h1[k];
      }
      return ans;
    };

    return Scope;

  })();

}).call(this);
